# Generated by Django 5.0.4 on 2024-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuppyApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pup',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
