# Generated by Django 5.0.4 on 2024-05-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuppyApi', '0003_rename_city_owner_username_remove_owner_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
