# Generated by Django 5.0.4 on 2024-05-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PuppyApi', '0005_pupparent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
